project_id = "pxtaefcpskjkjcucukgj"

[functions.generate-recommendations]
verify_jwt = true

[functions.qloo-api]
verify_jwt = true

[functions.gemini-api]
verify_jwt = true

[functions.taste-journey]
verify_jwt = true