// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxtaefcpskjkjcucukgj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4dGFlZmNwc2tqa2pjdWN1a2dqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NzI0NzEsImV4cCI6MjA2ODM0ODQ3MX0.nU2eiNsCjG3ViDoAS70npj8KKfGxcsuHVAigFe6M8_I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});